---
apiVersion: v1
kind: Service
metadata:
  name: db-hsvc
  namespace: db-ns
spec:
  ClusterIP: None
  selector:
    app: db-sts
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-sts
  namespace: dbns
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: db-hsvc
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      storageClassName: do-block-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: db-po
      labels:
        app: db
        name: db-sts
      spec:
        containers:
        - name: db-container
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: do_not_do_this
