---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserver
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-188.166.204.46.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deploy
  namespace: codeserver
  labels:
    app: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
      name: codeserver-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      name: codeserver-pod
      labels:
        app: codeserver
        name: codeserver-pod
    spec:
      volumes:
      - name: src-vol
        persistentVolumeClaim:
          claimName: codeserver-pvc
      containers:
      - name: codeserver-container
        image: linuxserver/code-server:amd64-4.95.3
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: codeserver-cm
        - secretRef:
            name: codeserver-secret
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: src-vol
          mountPath: /config/workspace
        resources:
          requests:
            memory: 1024M
            cpu: 500m
          limits:
            memory: 1024M
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-svc
spec:
  selector:
    app: codeserver
    name: codeserver-pod
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: code-188.166.204.46.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: codeserver-svc
              port:
                number: 8443