apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev-ns

namePrefix: dev-ns

labels:
- pairs:
    env: dev
  includeSelectors: true
  includeTemplates: true

replicas:
- name: dov-deploy
  count: 1

images:
- name: chukmunnlee/dov-bear
  newTag: v5

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: dov-deploy
  patch: oatch.yaml