---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
  template:
    metadata:
      name: deploy-app-pod
      namespace: bggns
      labels:
        app: bggapp
    spec:
      containers:
        - name: bgg-app-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
          envFrom:
            - configMapRef:
                name: bggdb-cm
            - secretRef:
                name: bggdb-secret
          ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
spec:
  type: ClusterIP
  selector:
    app: bggapp
  ports:
  - name: app
    port: 8080
    targetPort: 3000