---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    db: bggdb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: bggdb
  template:
    metadata:
      name: deploy-db-pod
      namespace: bggns
      labels:
        db: bggdb
    spec:
      containers:
      - name: bgg-database-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    db: bggdb
spec:
  type: ClusterIP
  selector:
    db: bggdb
  ports:
  - name: database
    port: 3306
