---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggdb-cm
  namespace: bggns
  labels:
    db: bggdb
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local


---
apiVersion: v1
kind: Secret
metadata:
  name: bggdb-secret
  namespace: bggns
  labels:
    db: bggdb
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=